# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_guestbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ParentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='guestbook',
            old_name='author',
            new_name='writer',
        ),
        migrations.RemoveField(
            model_name='guestbook',
            name='parentPost',
        ),
    ]
